### ISSUE TITLE
Elements not being removed

### ISSUE THREAD

**Issue by mindplay-dk** [luwes/sinuous#86] opened 2020-03-26 20:52 UTC
I've run into a bug, I think.

Have a look at this sandbox:

https://codesandbox.io/s/sinuous-hacker-news-v904j

Try switching between the menu items - previous components from every update are piling up somehow, not getting removed.

The problem is in stories:

```js
  return html`
    ${() => stories()
      ? stories().map((story, i) => Story({ ...story, index: i + 1 }))
      : Spinner()}
  `;
```

As you can see in [this version](https://codesandbox.io/s/sinuous-hacker-news-dqtf7) of the same sandbox, adding an extra wrapper `<div>` fixes it:

```js
  return html`
    <div>
      ${() => stories()
        ? stories().map((story, i) => Story({ ...story, index: i + 1 }))
        : Spinner()}
    </div>
  `;
```

Perhaps removals don't work for ranges and only for children of a parent node?

Is this a known limitation or a bug?

**Comment by luwes** [comment] 2020-03-26 22:44
thanks for reporting, that looks like a bug. I'm gonna look into this.

cool demo! another great addition for the readme examples if you like.

**Comment by mindplay-dk** [comment] 2020-03-27 09:51
> cool demo! another great addition for the readme examples if you like.

I'll let you know when it's done 🙂👍

**Comment by luwes** [comment] 2020-03-29 16:26
phew got it fixed, that was a hard nut to crack 😃 
https://codesandbox.io/s/sinuous-hacker-news-1g9vb

Until now Sinuous only added one extra empty text node as an ending marker for when fragments were added. A group id (an increasing number) got added to the first and last element of that fragment. at time of removal it was as simple as looking at the previous sibling of the end marker, if it had a group id then get the previous sibling until the same group id was found and remove that range of elements.

but in this case of nested conditional computeds with fragments the group id was overwritten at each addition of a nested fragment. also the first element in the fragment couldn't be relied on anymore as it could be replaced by something else or removed. I think the only solution for this problem was to add an additional marker that indicates the beginning of the fragment.

not all bad, the helloworld bundle size actually went down 0.02kB.
`sinuous/map` went up 0.1kB because the shared use of the `api.add()` method was removed.

cc @ryansolid just in case if you haven't covered this use case.

**Comment by ryansolid** [comment] 2020-03-29 16:49
Hey thanks for the mention. I moved off this approach to fragments last summer(when we had that blip where Solid was faster than VanillaJS) and went to deep nested array normalization. It is less performant in a few deeply nested cases but way simpler and it was actually faster in normal cases. But in any case interesting. You are right I didn't consider how through composition 2 fragments could end up adjacent to each other overwriting each marker. I might need to look at my hydration approach which uses markers similar way.

PS. I got this whole marker approach originally from lit-html. I thought I could optimize some out since they wrap every hole with a marker on each side. But clearly some edge scenarios I may have missed.

**Comment by luwes** [comment] 2020-03-29 20:27
thanks @ryansolid, ah yes I remember your change to arrays. I'll have to learn more about it, does it not require any markers then?

**Comment by ryansolid** [comment] 2020-03-30 00:42
Some markers but not for ranges in fragments. The whole thing gets treated as a single array of nodes. Keep in mind this was in unison of pulling the reactive system out of the reconciler. Which means 2 passes instead of 1. So you have some choices. I went my path for extensible control flow. There are definitely ways to do it single pass more optimal.

**Comment by luwes** [comment] 2020-03-30 02:25
it's a neat way to do it, I explored it in a PR. ended up around the same size, performance not fully sure yet. https://github.com/luwes/sinuous/pull/91

**Comment by luwes** [comment] 2020-03-30 03:08
closing here, the issue is repaired.

**Closed by luwes** 2020-03-30 03:08 UTC
Labels: bug

**Comment by mindplay-dk** [comment] 2020-03-30 15:11
Tested and confirmed - looks solid! 😀👌
