### ISSUE TITLE
Bug(?): setting an observable to the same value again triggers all dependencies

### ISSUE THREAD

**Issue by rozek** [luwes/sinuous#227] opened 2023-02-04 07:03 UTC
the following code

```javascript
  let a = observable(0)
  let b = computed(() => {
    console.log('computed: a() =',a())
    return 2*a()
  })
  subscribe(() => {
    console.log('subscribe: a() =',a(), 'b() =',b())
  })

  console.log('setting a')
  a(1)
  console.log('setting a to the same value again')
  a(1)
```

produces the following output

```
computed: a() = 0
subscribe: a() = 0 b() = 0
setting a
computed: a() = 1
subscribe: a() = 1 b() = 2
setting a to the same value again
computed: a() = 1
subscribe: a() = 1 b() = 2
```

This can lead to undesired changes in depending parts of an application and requires all users of an observable to explicitly check themselves whether the value they want to set differs from the current one

**Comment by heyheyhello** [comment] 2023-02-04 07:30
That's not a bug. I think you're assuming things based on some other observable libraries you may have seen? It's a design decision to skip recomputations for "same value" inputs. Keep in mind that the equality check (seen in libraries like Solid) that do "==" or "===" comes with its own issues such as banning the reuse of objects (which usually encourages "immutable style" code that has perf overhead).

**Comment by rozek** [comment] 2023-02-04 07:39
but the current implementation leads to problems with cyclic dependencies such as

```
  let Celsius    = observable(0)
  let Fahrenheit = observable(32)
  subscribe(() => { console.log('°F -> °C'); Celsius((Fahrenheit()-32)*5/9) })
  subscribe(() => { console.log('°C -> °F'); Fahrenheit(Celsius()*9/5+32) })

  console.log('Test 1: setting °C')
    Celsius(100)
  console.log('Test 2: setting °F')
    Fahrenheit(96)
```

**Comment by rozek** [comment] 2023-02-04 07:42
yes, computing "equality" is a problem of its own (which is why Java comes with an explicit method for it) but this should not be the reason for not preventing endless recursions...

**Comment by rozek** [comment] 2023-02-04 07:52
locally, I've solved this problem by adding the following code to "observable.js" just before the given new value is set:

```
    // do not set the same value again
    if (typeof comparator === 'function') {
      if (comparator(nextValue,value) == true) { return value }
    } else {
      if (nextValue === value) { return value }
    }
```

`comparator` is an optional extra argument I have added to the parameter list of `observable`

**Comment by heyheyhello** [comment] 2023-02-04 07:58
My hot take is that example is not a "problem". You've written explicitly cyclic code and then complained that it's cyclic...

If we switch to having an optional comparator parameter that defines a function to decide whether or not to update then we've simply moved the goal post: today it's already possible to change observables in a way that either do or do not update: by wrapping a value in an object and mutating that, OR by introducing another layer of signals to create a firewall (seen in frameworks like https://github.com/salsa-rs/salsa/issues/41)

Luwes could go either way but I don't think this is a bug.

**Comment by rozek** [comment] 2023-02-04 08:02
well, I have explicitly written cyclic code in order to illustrate the problem - and I am *not* complaining that it is cyclic: I just complain about "observable" running into an endless loop in such a case

**Comment by heyheyhello** [comment] 2023-02-04 08:15
Ah I see. I believe you want an error thrown like "Error: Cycle detected" then? I did this in my own reactive library and agree it would make sense

**Comment by rozek** [comment] 2023-02-04 08:22
No, I want the endless loop to be broken - cyclic dependencies are quite common and should be handled properly. Bi- or multidirectional converters are probably just the most obvious use case...

**Comment by rozek** [comment] 2023-02-04 10:28
I just read through the dicd of S.js a bit - S provides two different functions to set an "observable": S.data() and S.value()

S.data() is similar to observable(), S.value() to what I suggested (but without a "comparator" function)

**Comment by luwes** [comment] 2023-02-04 14:09
thanks for the feedback and help @rozek and @heyheyhello !

I'm going to close this one as I'm not planning to fix this. 
I'm entertaining the idea of using a different signal (observable) library altogether since there are so many now.

https://github.com/preactjs/signals/
https://github.com/WebReflection/usignal/
https://github.com/maverick-js/signals

and seems the community is agreeing on the name of "signal"

**Closed by luwes** 2023-02-04 14:09 UTC
